### ISSUE TITLE
Java and command invokers' builds fail with the same error code

### ISSUE THREAD

**Issue by fbiville** [projectriff/libfnbuildpack#47]
Both Java and command invoker build fail with error codes 102 (instantiation error) and 103 (launch layer contribution error) whereas they should probably use different error codes instead.

**Comment by ericbottard** [comment]
Where are those codes (now) defined? The spec used to not define specific codes, apart from 100

**Comment by fbiville** [comment]
Here: https://github.com/projectriff/riff-buildpack/blob/54f90e198db29134a814feff89692653246cbda1/build/main.go#L45.

It's probably not a big deal but the effort to have distinct error codes is also negligible.

**Comment by ericbottard** [comment]
Ah, I see. I thought this was now defined by pack.
I think using the same code is ok (as a matter of fact, as we make this extensible and define a contract for invokers, this may be necessary) but we may want to output some help text

**Comment by scothis** [comment]
@nebhale I assume this behavior is intentional, correct?

**Comment by nebhale** [comment]
Yep, I cleaned up the names of the error codes as well, but for as long as `libfnbuildpack` has existed [consistent error codes have been returned](https://github.com/projectriff/libfnbuildpack/commit/a0df38efac656b61010166fa6a4d0fe904a7a507#diff-e7d3b5cd309e7040cd581dea8ecb0e9cL29).

Even without `libfnbuildpack`, trying to ensure that there's no overlap of error codes across many repos doesn't seem to be a viable solution.
